# Generated by Django 5.0.2 on 2025-02-16 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 5, 21, 28, 509313, tzinfo=datetime.timezone.utc)),
        ),
    ]
