# Generated by Django 5.0.2 on 2025-02-16 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_meta_description_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 7, 48, 4, 163991, tzinfo=datetime.timezone.utc)),
        ),
    ]
